- hosts: wnodes
  tasks:
  - name: Restart a service
    win_service:
     name: spooler
     state: restarted

  - name: Set service startup mode to auto and ensure it is started
    win_service:
     name: spooler
     start_mode: auto
     state: started
